export const QUERY_KEYS = {
  pages: {
    home: {
      hero: "home:hero",
      about: "home:about",
      posters: "home:posters",
      products: "home:products",
      features: "home:features",
      gallery: "home:gallery",
      newsletter: "home:newsletter",
      whyChooseUs: "home:whyChooseUs",
      ourVision: "home:ourVision",
      ourGoals: "home:ourGoals",
      ourCustomers: "home:ourCustomers",
      factorsOfSuccess: "home:factorsOfSuccess",
    },
    privacyPolicy: "privacyPolicy",
    aboutUs: "about",
    contactUs: "contact",
    products: "products",
    cartContent: "cartContent",
    error: "error-page",
  },
  globalConfig: {
    appHeader: "appHeader",
    appFooter: "appFooter",
  },
  collections: {
    navigationLinks: "collections:navigationLinks",
    socialMedia: "collections:socialMedia",
    aboutItems: "collections:aboutItems",
    products: "collections:products",
    globalSEO: "collections:globalSEO",
    productUnits: "collections:productUnits",
    categories: "collections:categories",
  },
};
